language: cpp

jobs:
  include:
    - os: linux
      dist: focal
      compiler: gcc
    - os: osx
      osx_image: xcode12u
    - os: windows

before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain mingw-w64-x86_64-boost mingw-w64-x86_64-mpfr mingw-w64-x86_64-gmp mingw-w64-x86_64-nlohmann-json mingw-w64-x86_64-eigen3 mingw-w64-x86_64-lua mingw-w64-x86_64-swig
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE=mingw32-make  # so that Autotools can find it
        ;;
    esac
before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
      osx)
        brew cleanup
        ;;
    esac
cache:
    directories:
      - $HOME/AppData/Local/Temp/chocolatey
      - /C/tools/
      - $HOME/Library/Caches/Homebrew
   
install:
  - if [ $TRAVIS_OS_NAME == linux ]; then 
        sudo apt-get update && sudo apt-get install -y cmake wget tar libgmsh-dev libcgal-dev liblua5.3-dev libpython3-dev swig4.0;
        cd run/linux;
        ./genCBproject.sh;
        cd ../../;
    elif [ $TRAVIS_OS_NAME == osx ]; then 
        brew update && brew upgrade cmake && brew install wget gnu-tar llvm libomp unzip swig cgal lua python@3.7 nlohmann-json eigen;
        cd run/macos;
        ./genCBproject.sh;
        cd ../../;
    elif [ $TRAVIS_OS_NAME == windows ]; then 
        cd run/windows;
        ./genCBprojectMSYS2.sh;
        cd ../../;
    fi 

script:
  - cd build;
  - if [ $TRAVIS_OS_NAME == linux ]; then
        make;
    elif [ $TRAVIS_OS_NAME == osx ]; then
        make;
    elif [ $TRAVIS_OS_NAME == windows ]; then
        mingw32-make;
    fi
